apiVersion: v1
kind: Pod
metadata:
  name: client-pod-latest
  labels:
    component: web-latest
spec:
  containers:
    - name: client-pod
      image: stephengrider/multi-worker
      ports:
        - containerPort: 3000



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: client-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       component: web
#   template:
#     metadata:
#       labels:
#         component: web
#     spec:
#       containers:
#         - name: client-pod
#           image: stephengrider/multi-client
#           ports:
#             - containerPort: 3000
    