apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
#type NodePort exposes container to outside world
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31512
  selector:
    component: web-latest

