apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web-latest
  template:
    metadata:
      labels:
        component: web-latest
    spec:
      containers:
        - name: client-pod
          image: stephengrider/multi-client:v5
          ports:
            - containerPort: 3000